package com.sanmianti.output.pojo;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table product
 */
public class Product {
    /**
     * Database Column Remarks:
     *   商品ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_id
     *
     * @mbg.generated 2020-07-12 00:13:46
     */
    private String productId;

    /**
     * Database Column Remarks:
     *   商品名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_name
     *
     * @mbg.generated 2020-07-12 00:13:46
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_type
     *
     * @mbg.generated 2020-07-12 00:13:46
     */
    private String productType;

    /**
     * Database Column Remarks:
     *   出售价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.sale_price
     *
     * @mbg.generated 2020-07-12 00:13:46
     */
    private Long price;

    /**
     * Database Column Remarks:
     *   批发价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.purchase_price
     *
     * @mbg.generated 2020-07-12 00:13:46
     */
    private Integer purchasePrice;

    /**
     * Database Column Remarks:
     *   注册日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.regist_date
     *
     * @mbg.generated 2020-07-12 00:13:46
     */
    private Date registDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_id
     *
     * @return the value of product.product_id
     *
     * @mbg.generated 2020-07-12 00:13:46
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_id
     *
     * @param productId the value for product.product_id
     *
     * @mbg.generated 2020-07-12 00:13:46
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_name
     *
     * @return the value of product.product_name
     *
     * @mbg.generated 2020-07-12 00:13:46
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_name
     *
     * @param productName the value for product.product_name
     *
     * @mbg.generated 2020-07-12 00:13:46
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_type
     *
     * @return the value of product.product_type
     *
     * @mbg.generated 2020-07-12 00:13:46
     */
    public String getProductType() {
        return productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_type
     *
     * @param productType the value for product.product_type
     *
     * @mbg.generated 2020-07-12 00:13:46
     */
    public void setProductType(String productType) {
        this.productType = productType == null ? null : productType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.sale_price
     *
     * @return the value of product.sale_price
     *
     * @mbg.generated 2020-07-12 00:13:46
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.sale_price
     *
     * @param price the value for product.sale_price
     *
     * @mbg.generated 2020-07-12 00:13:46
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.purchase_price
     *
     * @return the value of product.purchase_price
     *
     * @mbg.generated 2020-07-12 00:13:46
     */
    public Integer getPurchasePrice() {
        return purchasePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.purchase_price
     *
     * @param purchasePrice the value for product.purchase_price
     *
     * @mbg.generated 2020-07-12 00:13:46
     */
    public void setPurchasePrice(Integer purchasePrice) {
        this.purchasePrice = purchasePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.regist_date
     *
     * @return the value of product.regist_date
     *
     * @mbg.generated 2020-07-12 00:13:46
     */
    public Date getRegistDate() {
        return registDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.regist_date
     *
     * @param registDate the value for product.regist_date
     *
     * @mbg.generated 2020-07-12 00:13:46
     */
    public void setRegistDate(Date registDate) {
        this.registDate = registDate;
    }
}